// AI-generated by contractor using low-effort Copilot prompt
// Status: UNREVIEWED

import { ProjectModel, Project } from './Project';

export class ProjectService {
  private projectModel: ProjectModel;

  constructor(db: any) {
    this.projectModel = new ProjectModel(db);
  }

  async createProject(data: any): Promise<Project> {
    // Validate input
    if (!data.name || !data.teamId) {
      throw new Error('Name and teamId are required');
    }
    return this.projectModel.create(data);
  }

  async updateProjectStatus(projectId: string, newStatus: string): Promise<Project> {
    const validStatuses = ['active', 'archived', 'closed'];
    if (!validStatuses.includes(newStatus)) {
      throw new Error('Invalid status');
    }
    return this.projectModel.updateStatus(projectId, newStatus);
  }

  async getProjectsByTeam(teamId: string): Promise<Project[]> {
    if (!teamId) {
      throw new Error('TeamId is required');
    }
    return this.projectModel.getByTeam(teamId);
  }

  async deleteProject(projectId: string): Promise<boolean> {
    if (!projectId) {
      throw new Error('ProjectId is required');
    }
    return this.projectModel.delete(projectId);
  }

  async getProject(projectId: string): Promise<Project | null> {
    if (!projectId) {
      throw new Error('ProjectId is required');
    }
    return this.projectModel.getById(projectId);
  }

  async getAllProjects(): Promise<Project[]> {
    return this.projectModel.getAllProjects();
  }
}
