// AI-generated by contractor using low-effort Copilot prompt
// Status: UNREVIEWED

export interface Project {
  id: string;
  name: string;
  description: string;
  teamId: string;
  status: 'active' | 'archived' | 'closed';
  createdAt: Date;
  updatedAt: Date;
}

export interface Milestone {
  id: string;
  projectId: string;
  title: string;
  dueDate: Date;
  status: 'pending' | 'in_progress' | 'completed';
  createdAt: Date;
  updatedAt: Date;
}

export class ProjectModel {
  constructor(private db: any) {}

  async create(data: Omit<Project, 'id' | 'createdAt' | 'updatedAt'>): Promise<Project> {
    const query = `
      INSERT INTO projects (name, description, teamId, status)
      VALUES ($1, $2, $3, $4)
      RETURNING *
    `;
    const result = await this.db.query(query, [
      data.name,
      data.description,
      data.teamId,
      data.status || 'active'
    ]);
    return result.rows[0];
  }

  async getById(id: string): Promise<Project | null> {
    const query = 'SELECT * FROM projects WHERE id = $1';
    const result = await this.db.query(query, [id]);
    return result.rows[0] || null;
  }

  async getByTeam(teamId: string): Promise<Project[]> {
    const query = 'SELECT * FROM projects WHERE teamId = $1';
    const result = await this.db.query(query, [teamId]);
    return result.rows;
  }

  async updateStatus(id: string, status: string): Promise<Project> {
    const query = `
      UPDATE projects
      SET status = $1, updatedAt = NOW()
      WHERE id = $2
      RETURNING *
    `;
    const result = await this.db.query(query, [status, id]);
    return result.rows[0];
  }

  async delete(id: string): Promise<boolean> {
    const query = 'DELETE FROM projects WHERE id = $1';
    const result = await this.db.query(query, [id]);
    return result.rowCount > 0;
  }

  async getAllProjects(): Promise<Project[]> {
    const query = 'SELECT * FROM projects';
    const result = await this.db.query(query);
    return result.rows;
  }
}
